version: '3.3'

services:
  mysql:
    container_name: ReelLove-MySQL
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    user: root
    ports:
      - "3306:3306"
volumes:
  mysql_data: